import { toHindiMenuText } from "@/lib/hindi-menu";

export type CustomerLocale = "en" | "hi";

export const CUSTOMER_LANG_KEY = "cafe-lang";

const COPY = {
  en: {
    language: "हिन्दी",
    languageHint: "English",
    navHome: "Home",
    navReserve: "Reserve",
    navMyOrders: "My orders",
    navAdmin: "Admin",
    navOrder: "Order",
    noAppNeeded: "No app needed — works in your phone browser.",
    callWaiter: "Call waiter",
    requestBill: "Request bill",
    waiterSent: "Waiter notified",
    billSent: "Bill requested",
    couldNotSend: "Could not send",
    waitTime: "Est. wait",
    minutes: "min",
    wifi: "Wi-Fi",
    busy: "Kitchen is full — new orders are paused. Please wait or ask staff.",
    veg: "Veg",
    nonVeg: "Non-veg",
    jain: "Jain",
    all: "All",
    notes: "Notes for kitchen",
    notesPlaceholder: "e.g. less sugar, no onion",
    spice: "Spice",
    mild: "Mild",
    medium: "Medium",
    hot: "Hot",
    none: "No spice",
    coupon: "Coupon code",
    apply: "Apply",
    invalidCoupon: "Invalid coupon",
    loyalty: "Loyalty points",
    redeem: "Redeem",
    takeaway: "Takeaway",
    dineIn: "Dine in",
    reorder: "Reorder last",
    splitBill: "Split bill",
    splitBetween: "Split between",
    eachPays: "Each pays",
    sendWhatsApp: "Send bill on WhatsApp",
    reserve: "Reserve a table",
    table: "Table",
    orderingAs: "Ordering as",
    viewOrderStatus: "View order status →",
    tapAdd: "Tap ADD to build your order",
    searchPlaceholder: "Search dishes, offers…",
    searchAria: "Search menu",
    clearSearch: "Clear search",
    categoriesAria: "Menu categories",
    offersTitle: "Offers & combos",
    offersSubtitle: "Bundle deals — add a full combo in one tap",
    loadingMenu: "Loading menu…",
    noMatch: "No items match",
    topRated: "Top rated",
    popularPicks: "Popular picks",
    suggested: "Suggested for you",
    topRatedSub: "Loved by guests — add in one tap",
    popularSub: "Guest favourites — add in one tap",
    suggestedSub: "Great choices to start your order",
    preparingMore: "Preparing — tap ADD to get more",
    preparingAdd: "Preparing — add more?",
    kitchenPreparing: "Kitchen is preparing this — you can still add more",
    allergens: "Allergens",
    inCart: "in cart",
    addToOrder: "Add to order",
    add: "ADD",
    viewCart: "View cart",
    view: "VIEW →",
    yourCart: "Your cart",
    menu: "← Menu",
    items: "item",
    itemsPlural: "items",
    itemsTotal: "Items total",
    toPay: "To pay",
    couponOff: "Coupon",
    placeOrder: "Place order",
    orderPlaced: "Order placed successfully",
    sendingOrder: "Sending order…",
    confirm: "Confirm",
    almostDone: "Almost done — your details",
    yourName: "Your name",
    phoneNumber: "Phone number",
    nameRequired: "Please enter your name",
    phoneRequired: "Please enter your phone number",
    phoneInvalid: "Please enter a valid 10-digit phone number",
    placeFailed: "Could not place order",
    other: "Other",
    otherTables: "Other tables are ordering",
    loadMenuError: "Could not load menu — check your internet connection",
    closeItem: "Close item details",
    closeCart: "Close order sheet",
    decreaseQty: "Decrease quantity",
    increaseQty: "Increase quantity",
    received: "Received",
    preparing: "Preparing",
    served: "Served",
    cancelled: "Cancelled",
    enjoyMeal: "Enjoy your meal!",
    billReady: "Your bill is ready below. Thanks",
    orderCancelled: "Order cancelled",
    contactStaff: "Please contact staff if you need help,",
    kitchenOnIt: "Kitchen is on it",
    hangTight: "Hang tight",
    wellBring: "— we'll bring it to",
    orderReceived: "Order received",
    trackingOrder: "— tracking your order for",
    yourBill: "Your bill",
    orderDetails: "Order details",
    loadingStatus: "Loading status…",
    noActiveOrders: "No active orders",
    rateDishes: "Rate your dishes",
    thanksFeedback: "Thanks for your feedback!",
    howWasDish: "How was this dish?",
    optionalComment: "Optional comment…",
    submitFeedback: "Submit feedback",
    saving: "Saving…",
    selectStars: "Please select a star rating",
    orderCancelledHelp: "Your order was cancelled. Please contact staff if you need help.",
    enjoyRate: "Enjoy your meal! Rate your dishes above to help us improve.",
    orderMore: "Order more items",
    addMore: "Add more items",
    statusAuto: "Status updates automatically",
    there: "there",
    thanks: "Thanks",
    reserveTitle: "Reserve a table",
    reserveOk: "Reserved. We'll confirm with you on WhatsApp or when you arrive.",
    guestName: "Your name",
    phone: "Phone",
    partySize: "Guests",
    dateTime: "Date and time",
    datePlaceholder: "Select date and time",
    optionalNote: "Optional note",
    bookTable: "Book table",
    booking: "Booking…",
    couldNotBook: "Could not book",
    myOrders: "My orders",
    loading: "Loading…",
    recentOnDevice: "Your most recent order on this device",
    ordersLinked: "Orders linked to your verified account",
    verifyToSee: "Verify with email (free) or phone to see past orders",
    emailFree: "Email (free)",
    phoneSms: "Phone (SMS)",
    emailAddress: "Email address",
    sendCode: "Send verification code",
    sendingCode: "Sending code…",
    verificationCode: "Verification code",
    codePlaceholder: "6-digit code",
    verifyView: "Verify & view orders",
    verifying: "Verifying…",
    useDifferent: "Use a different",
    email: "email",
    number: "number",
    codeSentTo: "Code sent to",
    recentDevice: "Recent order on this device",
    lookUpAll: "Look up all past orders →",
    verified: "Verified",
    signOut: "Sign out",
    noOrders: "No orders found",
    scanQrToOrder: "Scan table QR to order",
    backHome: "← Back to home",
    saveReorder: "Save to reorder at table",
    savedReorder: "Saved — scan your table QR to add these items",
    adminLogin: "Admin login",
  },
  hi: {
    language: "English",
    languageHint: "हिन्दी",
    navHome: "होम",
    navReserve: "रिज़र्व",
    navMyOrders: "मेरे ऑर्डर",
    navAdmin: "एडमिन",
    navOrder: "ऑर्डर",
    noAppNeeded: "ऐप की ज़रूरत नहीं — फ़ोन ब्राउज़र में चलता है।",
    callWaiter: "वेटर बुलाएँ",
    requestBill: "बिल मँगवाएँ",
    waiterSent: "वेटर को सूचना गई",
    billSent: "बिल का अनुरोध गया",
    couldNotSend: "भेज नहीं सके",
    waitTime: "अनुमानित प्रतीक्षा",
    minutes: "मिनट",
    wifi: "वाई-फाई",
    busy: "किचन व्यस्त है — नए ऑर्डर रुक गए हैं। कृपया प्रतीक्षा करें।",
    veg: "वेज",
    nonVeg: "नॉन-वेज",
    jain: "जैन",
    all: "सभी",
    notes: "किचन के लिए नोट",
    notesPlaceholder: "जैसे कम चीनी, प्याज़ नहीं",
    spice: "मिर्च",
    mild: "कम",
    medium: "मध्यम",
    hot: "तेज़",
    none: "नहीं",
    coupon: "कूपन कोड",
    apply: "लागू करें",
    invalidCoupon: "अमान्य कूपन",
    loyalty: "लॉयल्टी अंक",
    redeem: "रिडीम",
    takeaway: "पार्सल",
    dineIn: "टेबल पर",
    reorder: "पिछला ऑर्डर दोहराएँ",
    splitBill: "बिल बाँटें",
    splitBetween: "बाँटें",
    eachPays: "प्रत्येक का हिस्सा",
    sendWhatsApp: "व्हाट्सऐप पर बिल भेजें",
    reserve: "टेबल बुक करें",
    table: "टेबल",
    orderingAs: "ऑर्डर कर रहे हैं",
    viewOrderStatus: "ऑर्डर स्थिति देखें →",
    tapAdd: "आइटम जोड़ने के लिए ADD दबाएँ",
    searchPlaceholder: "डिश, ऑफ़र खोजें…",
    searchAria: "मेनू खोजें",
    clearSearch: "खोज साफ़ करें",
    categoriesAria: "मेनू श्रेणियाँ",
    offersTitle: "ऑफ़र और कॉम्बो",
    offersSubtitle: "एक टैप में पूरा कॉम्बो जोड़ें",
    loadingMenu: "मेनू लोड हो रहा है…",
    noMatch: "कोई आइटम नहीं मिला",
    topRated: "टॉप रेटेड",
    popularPicks: "लोकप्रिय",
    suggested: "आपके लिए सुझाव",
    topRatedSub: "मेहमानों को पसंद — एक टैप में जोड़ें",
    popularSub: "पसंदीदा व्यंजन — एक टैप में जोड़ें",
    suggestedSub: "ऑर्डर शुरू करने के लिए बढ़िया विकल्प",
    preparingMore: "बन रहा है — और जोड़ने के लिए ADD दबाएँ",
    preparingAdd: "बन रहा है — और जोड़ें?",
    kitchenPreparing: "किचन इसे बना रहा है — आप और जोड़ सकते हैं",
    allergens: "एलर्जी",
    inCart: "कार्ट में",
    addToOrder: "ऑर्डर में जोड़ें",
    add: "जोड़ें",
    viewCart: "कार्ट देखें",
    view: "देखें →",
    yourCart: "आपका कार्ट",
    menu: "← मेनू",
    items: "आइटम",
    itemsPlural: "आइटम",
    itemsTotal: "कुल आइटम",
    toPay: "देना है",
    couponOff: "कूपन",
    placeOrder: "ऑर्डर करें",
    orderPlaced: "ऑर्डर लग गया",
    sendingOrder: "ऑर्डर भेजा जा रहा है…",
    confirm: "पुष्टि करें",
    almostDone: "बस नाम और फ़ोन",
    yourName: "आपका नाम",
    phoneNumber: "फ़ोन नंबर",
    nameRequired: "कृपया अपना नाम लिखें",
    phoneRequired: "कृपया फ़ोन नंबर लिखें",
    phoneInvalid: "कृपया सही 10 अंकों का फ़ोन नंबर लिखें",
    placeFailed: "ऑर्डर नहीं लग सका",
    other: "अन्य",
    otherTables: "दूसरी टेबल ऑर्डर कर रही हैं",
    loadMenuError: "मेनू नहीं खुला — इंटरनेट जाँचें",
    closeItem: "बंद करें",
    closeCart: "कार्ट बंद करें",
    decreaseQty: "मात्रा घटाएँ",
    increaseQty: "मात्रा बढ़ाएँ",
    received: "मिला",
    preparing: "बन रहा है",
    served: "परोसा गया",
    cancelled: "रद्द",
    enjoyMeal: "भोजन का आनंद लें!",
    billReady: "आपका बिल नीचे है। धन्यवाद",
    orderCancelled: "ऑर्डर रद्द हो गया",
    contactStaff: "मदद के लिए स्टाफ़ से बात करें,",
    kitchenOnIt: "किचन बना रहा है",
    hangTight: "ज़रा रुकिए",
    wellBring: "— हम ले आएंगे",
    orderReceived: "ऑर्डर मिल गया",
    trackingOrder: "— आपका ऑर्डर ट्रैक हो रहा है",
    yourBill: "आपका बिल",
    orderDetails: "ऑर्डर विवरण",
    loadingStatus: "स्थिति लोड हो रही है…",
    noActiveOrders: "कोई चालू ऑर्डर नहीं",
    rateDishes: "व्यंजन रेट करें",
    thanksFeedback: "आपकी राय के लिए धन्यवाद!",
    howWasDish: "यह डिश कैसी थी?",
    optionalComment: "वैकल्पिक टिप्पणी…",
    submitFeedback: "राय भेजें",
    saving: "सेव हो रहा है…",
    selectStars: "कृपया स्टार रेटिंग चुनें",
    orderCancelledHelp: "ऑर्डर रद्द हो गया। मदद के लिए स्टाफ़ से बात करें।",
    enjoyRate: "भोजन का आनंद लें! सुधार के लिए ऊपर रेट करें।",
    orderMore: "और ऑर्डर करें",
    addMore: "और आइटम जोड़ें",
    statusAuto: "स्थिति अपने आप अपडेट होती है",
    there: "जी",
    thanks: "धन्यवाद",
    reserveTitle: "टेबल बुक करें",
    reserveOk: "बुक हो गई। हम व्हाट्सऐप पर या आने पर पुष्टि करेंगे।",
    guestName: "आपका नाम",
    phone: "फ़ोन",
    partySize: "मेहमान",
    dateTime: "तारीख और समय",
    datePlaceholder: "तारीख और समय चुनें",
    optionalNote: "वैकल्पिक नोट",
    bookTable: "टेबल बुक करें",
    booking: "बुक हो रहा है…",
    couldNotBook: "बुक नहीं हो सकी",
    myOrders: "मेरे ऑर्डर",
    loading: "लोड हो रहा है…",
    recentOnDevice: "इस फ़ोन पर आपका हाल का ऑर्डर",
    ordersLinked: "आपके खाते से जुड़े ऑर्डर",
    verifyToSee: "पुराने ऑर्डर देखने के लिए ईमेल (मुफ़्त) या फ़ोन से पुष्टि करें",
    emailFree: "ईमेल (मुफ़्त)",
    phoneSms: "फ़ोन (SMS)",
    emailAddress: "ईमेल पता",
    sendCode: "कोड भेजें",
    sendingCode: "कोड भेजा जा रहा है…",
    verificationCode: "पुष्टि कोड",
    codePlaceholder: "6 अंकों का कोड",
    verifyView: "पुष्टि करें और ऑर्डर देखें",
    verifying: "जाँच हो रही है…",
    useDifferent: "दूसरा इस्तेमाल करें",
    email: "ईमेल",
    number: "नंबर",
    codeSentTo: "कोड भेजा गया",
    recentDevice: "इस फ़ोन पर हाल का ऑर्डर",
    lookUpAll: "सारे पुराने ऑर्डर देखें →",
    verified: "पुष्टि हो गई",
    signOut: "साइन आउट",
    noOrders: "कोई ऑर्डर नहीं मिला",
    scanQrToOrder: "ऑर्डर के लिए टेबल QR स्कैन करें",
    backHome: "← होम पर जाएँ",
    saveReorder: "टेबल पर दोबारा ऑर्डर के लिए सेव करें",
    savedReorder: "सेव हो गया — आइटम जोड़ने के लिए टेबल QR स्कैन करें",
    adminLogin: "एडमिन लॉगिन",
  },
} as const;

export type CustomerCopy = {
  [K in keyof typeof COPY.en]: string;
};

export function getCustomerCopy(locale: CustomerLocale): CustomerCopy {
  return (COPY[locale] || COPY.en) as CustomerCopy;
}

export function customerInputLang(locale: CustomerLocale): "hi-IN" | "en" {
  return locale === "hi" ? "hi-IN" : "en";
}

export function displayMenuText(text: string, locale: CustomerLocale): string {
  if (locale !== "hi" || !text) return text;
  return toHindiMenuText(text);
}

export function displaySpiceLabel(
  level: string | undefined,
  copy: CustomerCopy
): string {
  if (!level) return "";
  const key = level.trim().toLowerCase();
  if (key === "mild") return copy.mild;
  if (key === "medium") return copy.medium;
  if (key === "hot") return copy.hot;
  if (key === "none") return copy.none;
  return level;
}

export function displayItemName(
  item: { name: string; name_hi?: string | null },
  locale: CustomerLocale
): string {
  if (locale !== "hi") return item.name;
  if (item.name_hi?.trim()) return item.name_hi.trim();
  return toHindiMenuText(item.name);
}

export function displayItemDescription(
  item: { description: string; description_hi?: string | null },
  locale: CustomerLocale
): string {
  if (locale !== "hi") return item.description || "";
  if (item.description_hi?.trim()) return item.description_hi.trim();
  return item.description ? toHindiMenuText(item.description) : "";
}
