-- Keffi menu — run in Supabase SQL Editor to replace the sample menu
-- Safe: order_items store item names, not menu_item IDs

delete from menu_items;
delete from menu_categories;

insert into menu_categories (name, sort_order) values
  ('Soup', 1),
  ('Salads', 2),
  ('Starters', 3),
  ('Steam', 4),
  ('Burgers', 5),
  ('Sandwiches', 6),
  ('From the Wok', 7),
  ('Rice', 8),
  ('Sharing Bites', 9),
  ('Mouth-Melting Cheese Bites', 10),
  ('Keffi Signatures', 11),
  ('Pizza — Thin Crust', 12),
  ('Pasta', 13),
  ('Desserts', 14),
  ('Add-ons', 15);

insert into menu_items (category_id, name, description, price, image_url)
select c.id, v.name, v.description, v.price, v.image_url
from (values
  ('Soup', 'Hot & Sour Soup (Veg)', '', 245, null),
  ('Soup', 'Hot & Sour Soup (Chicken)', '', 245, null),
  ('Soup', 'Manchow Soup (Veg)', '', 245, null),
  ('Soup', 'Manchow Soup (Chicken)', '', 245, null),
  ('Salads', 'Classic Caesar Salad', '', 395, null),
  ('Salads', 'Pickled Fruits & Nut Salad with Feta Cheese', '', 445, null),
  ('Starters', 'Golden Silk Spring Roll', '', 295, null),
  ('Starters', 'Chicken Teriyaki Spring Roll', '', 315, null),
  ('Starters', 'Street Chilli Chicken', '', 349, null),
  ('Starters', 'Thai Chilli Paneer', '', 395, null),
  ('Starters', 'Crispy Corn Salt & Pepper', '', 295, null),
  ('Starters', 'Chongqing Mushroom', '', 295, null),
  ('Starters', 'Honey Chilli Potato', '', 249, null),
  ('Steam', 'Thai Chicken Dumpling', '', 395, null),
  ('Steam', 'Cream Cheese Truffle Mushroom Dumpling', '', 395, null),
  ('Steam', 'Jhol Momo Chicken', '', 395, null),
  ('Steam', 'Jhol Momo Veg', '', 349, null),
  ('Burgers', 'Tokyo Veg Katsu Burger', '', 249, null),
  ('Burgers', 'Seoul Fried Chicken Burger', '', 315, null),
  ('Burgers', 'Herb Mushroom Burger', '', 295, null),
  ('Burgers', 'Thecha Chicken Burger', '', 345, null),
  ('Sandwiches', 'Chicken Club Sandwich', '', 395, null),
  ('Sandwiches', 'Korean Crispy Chicken Sandwich', '', 349, null),
  ('Sandwiches', 'Mouth Melting Vegetable Cheese Sandwich', '', 315, null),
  ('Sandwiches', 'Tuscan Mushroom Melt', '', 249, null),
  ('From the Wok', 'Wok Tossed Noodles', '', 349, null),
  ('From the Wok', 'Masala Maggi Monsoon Bowl', '', 245, null),
  ('From the Wok', 'Spicy Chilli Bowl', '', 349, null),
  ('From the Wok', 'Korean Kimchi Bowl', '', 349, null),
  ('From the Wok', 'Chilli Basil Noodles', '', 315, null),
  ('From the Wok', 'Chilli Garlic Noodles', '', 315, null),
  ('From the Wok', 'Singapore Laksa Bowl', '', 345, null),
  ('Rice', 'Chilli Garlic Fried Rice', '', 345, null),
  ('Rice', 'Fried Rice', '', 315, null),
  ('Rice', 'Chicken Fried Rice', '', 395, null),
  ('Sharing Bites', 'Salted Fries', '', 149, null),
  ('Sharing Bites', 'Peri Peri Fries', '', 159, null),
  ('Sharing Bites', 'Cheese Fries', '', 179, null),
  ('Sharing Bites', 'Mexican Potato Wedges', '', 195, null),
  ('Mouth-Melting Cheese Bites', 'Mozzarella Cheese Sticks', '', 195, null),
  ('Mouth-Melting Cheese Bites', 'Cheese Balls', '', 195, null),
  ('Mouth-Melting Cheese Bites', 'Crispy Onion Rings', '', 195, null),
  ('Mouth-Melting Cheese Bites', 'Chipotle Chicken Taco', '', 245, null),
  ('Mouth-Melting Cheese Bites', 'Tangy Cottage Cheese Taco', '', 245, null),
  ('Keffi Signatures', 'Falafel Platter', '', 295, null),
  ('Keffi Signatures', 'Nachos with Salsa and Sour Cream', '', 245, null),
  ('Keffi Signatures', 'Cheese Garlic Bread', '', 195, null),
  ('Pizza — Thin Crust', 'Margherita Pizza', '', 395, null),
  ('Pizza — Thin Crust', 'Mutton Pepperoni Pizza', '', 445, null),
  ('Pizza — Thin Crust', 'Chicken Tikka Pizza', '', 395, null),
  ('Pizza — Thin Crust', 'Bianca Pizza', '', 345, null),
  ('Pizza — Thin Crust', 'Farmhouse Vegetable Pizza', '', 395, null),
  ('Pasta', 'Spaghetti — Pomodoro', 'Tomato basil sauce', 345, null),
  ('Pasta', 'Spaghetti — Arrabbiata', 'Spicy tomato sauce', 345, null),
  ('Pasta', 'Spaghetti — Aglio e Olio', 'Garlic and olive oil', 345, null),
  ('Pasta', 'Spaghetti — Alfredo', 'Creamy cheese sauce', 345, null),
  ('Pasta', 'Spaghetti — Pink Sauce', 'Tomato-cream sauce', 345, null),
  ('Pasta', 'Penne — Pomodoro', 'Tomato basil sauce', 345, null),
  ('Pasta', 'Penne — Arrabbiata', 'Spicy tomato sauce', 345, null),
  ('Pasta', 'Penne — Aglio e Olio', 'Garlic and olive oil', 345, null),
  ('Pasta', 'Penne — Alfredo', 'Creamy cheese sauce', 345, null),
  ('Pasta', 'Penne — Pink Sauce', 'Tomato-cream sauce', 345, null),
  ('Pasta', 'Fettuccine — Pomodoro', 'Tomato basil sauce', 345, null),
  ('Pasta', 'Fettuccine — Arrabbiata', 'Spicy tomato sauce', 345, null),
  ('Pasta', 'Fettuccine — Aglio e Olio', 'Garlic and olive oil', 345, null),
  ('Pasta', 'Fettuccine — Alfredo', 'Creamy cheese sauce', 345, null),
  ('Pasta', 'Fettuccine — Pink Sauce', 'Tomato-cream sauce', 345, null),
  ('Desserts', 'Hot Chocolate Brownie', '', 245, null),
  ('Desserts', 'Chocolate Crunch Cake', '', 245, null),
  ('Desserts', 'Baked Yogurt & Granola', '', 225, null),
  ('Desserts', 'Vegan Chocolate Cake', '', 245, null),
  ('Desserts', 'No-Bake Cheesecake', '', 265, null),
  ('Add-ons', 'Chicken', 'Soup, salad, or pasta', 70, null),
  ('Add-ons', 'Prawns', 'Pasta add-on', 90, null),
  ('Add-ons', 'Vegetable', 'Pasta add-on', 70, null),
  ('Add-ons', 'Cottage Cheese', 'Pasta add-on', 99, null)
) as v(cat, name, description, price, image_url)
join menu_categories c on c.name = v.cat;

update cafe_settings
set app_name = 'Keffi',
    tagline = 'Crafted to Refresh',
    logo_url = '/keffi-logo.png'
where id = 1;
