-- Keffi menu — run in Supabase SQL Editor to replace the sample menu
-- Safe: order_items store item names, not menu_item IDs

delete from menu_items;
delete from menu_categories;

insert into menu_categories (name, sort_order) values
  ('Soup', 1),
  ('Salads', 2),
  ('Starters', 3),
  ('Steam', 4),
  ('Burgers', 5),
  ('Sandwiches', 6),
  ('From the Wok', 7),
  ('Rice', 8),
  ('Sharing Bites', 9),
  ('Mouth-Melting Cheese Bites', 10),
  ('Keffi Signatures', 11),
  ('Pizza — Thin Crust', 12),
  ('Pasta', 13),
  ('Desserts', 14),
  ('Add-ons', 15);

insert into menu_items (category_id, name, description, price, image_url)
select c.id, v.name, v.description, v.price, v.image_url
from (values
  ('Soup', 'Hot & Sour Soup (Veg)', '', 245, '/menu/items/hot-sour-soup-veg.jpg'),
  ('Soup', 'Hot & Sour Soup (Chicken)', '', 245, '/menu/items/hot-sour-soup-chicken.jpg'),
  ('Soup', 'Manchow Soup (Veg)', '', 245, '/menu/items/manchow-soup-veg.jpg'),
  ('Soup', 'Manchow Soup (Chicken)', '', 245, '/menu/items/manchow-soup-chicken.jpg'),
  ('Salads', 'Classic Caesar Salad', '', 395, '/menu/items/classic-caesar-salad.jpg'),
  ('Salads', 'Pickled Fruits & Nut Salad with Feta Cheese', '', 445, '/menu/items/pickled-fruits-nut-salad-with-feta-cheese.jpg'),
  ('Starters', 'Golden Silk Spring Roll', '', 295, '/menu/items/golden-silk-spring-roll.jpg'),
  ('Starters', 'Chicken Teriyaki Spring Roll', '', 315, '/menu/items/chicken-teriyaki-spring-roll.jpg'),
  ('Starters', 'Street Chilli Chicken', '', 349, '/menu/items/street-chilli-chicken.jpg'),
  ('Starters', 'Thai Chilli Paneer', '', 395, '/menu/items/thai-chilli-paneer.jpg'),
  ('Starters', 'Crispy Corn Salt & Pepper', '', 295, '/menu/items/crispy-corn-salt-pepper.jpg'),
  ('Starters', 'Chongqing Mushroom', '', 295, '/menu/items/chongqing-mushroom.jpg'),
  ('Starters', 'Honey Chilli Potato', '', 249, '/menu/items/honey-chilli-potato.jpg'),
  ('Steam', 'Thai Chicken Dumpling', '', 395, '/menu/items/thai-chicken-dumpling.jpg'),
  ('Steam', 'Cream Cheese Truffle Mushroom Dumpling', '', 395, '/menu/items/cream-cheese-truffle-mushroom-dumpling.jpg'),
  ('Steam', 'Jhol Momo Chicken', '', 395, '/menu/items/jhol-momo-chicken.jpg'),
  ('Steam', 'Jhol Momo Veg', '', 349, '/menu/items/jhol-momo-veg.jpg'),
  ('Burgers', 'Tokyo Veg Katsu Burger', '', 249, '/menu/items/tokyo-veg-katsu-burger.jpg'),
  ('Burgers', 'Seoul Fried Chicken Burger', '', 315, '/menu/items/seoul-fried-chicken-burger.jpg'),
  ('Burgers', 'Herb Mushroom Burger', '', 295, '/menu/items/herb-mushroom-burger.jpg'),
  ('Burgers', 'Thecha Chicken Burger', '', 345, '/menu/items/thecha-chicken-burger.jpg'),
  ('Sandwiches', 'Chicken Club Sandwich', '', 395, '/menu/items/chicken-club-sandwich.jpg'),
  ('Sandwiches', 'Korean Crispy Chicken Sandwich', '', 349, '/menu/items/korean-crispy-chicken-sandwich.jpg'),
  ('Sandwiches', 'Mouth Melting Vegetable Cheese Sandwich', '', 315, '/menu/items/mouth-melting-vegetable-cheese-sandwich.jpg'),
  ('Sandwiches', 'Tuscan Mushroom Melt', '', 249, '/menu/items/tuscan-mushroom-melt.jpg'),
  ('From the Wok', 'Wok Tossed Noodles', '', 349, '/menu/items/wok-tossed-noodles.jpg'),
  ('From the Wok', 'Masala Maggi Monsoon Bowl', '', 245, '/menu/items/masala-maggi-monsoon-bowl.jpg'),
  ('From the Wok', 'Spicy Chilli Bowl', '', 349, '/menu/items/spicy-chilli-bowl.jpg'),
  ('From the Wok', 'Korean Kimchi Bowl', '', 349, '/menu/items/korean-kimchi-bowl.jpg'),
  ('From the Wok', 'Chilli Basil Noodles', '', 315, '/menu/items/chilli-basil-noodles.jpg'),
  ('From the Wok', 'Chilli Garlic Noodles', '', 315, '/menu/items/chilli-garlic-noodles.jpg'),
  ('From the Wok', 'Singapore Laksa Bowl', '', 345, '/menu/items/singapore-laksa-bowl.jpg'),
  ('Rice', 'Chilli Garlic Fried Rice', '', 345, '/menu/items/chilli-garlic-fried-rice.jpg'),
  ('Rice', 'Fried Rice', '', 315, '/menu/items/fried-rice.jpg'),
  ('Rice', 'Chicken Fried Rice', '', 395, '/menu/items/chicken-fried-rice.jpg'),
  ('Sharing Bites', 'Salted Fries', '', 149, '/menu/items/salted-fries.jpg'),
  ('Sharing Bites', 'Peri Peri Fries', '', 159, '/menu/items/peri-peri-fries.jpg'),
  ('Sharing Bites', 'Cheese Fries', '', 179, '/menu/items/cheese-fries.jpg'),
  ('Sharing Bites', 'Mexican Potato Wedges', '', 195, '/menu/items/mexican-potato-wedges.jpg'),
  ('Mouth-Melting Cheese Bites', 'Mozzarella Cheese Sticks', '', 195, '/menu/items/mozzarella-cheese-sticks.jpg'),
  ('Mouth-Melting Cheese Bites', 'Cheese Balls', '', 195, '/menu/items/cheese-balls.jpg'),
  ('Mouth-Melting Cheese Bites', 'Crispy Onion Rings', '', 195, '/menu/items/crispy-onion-rings.jpg'),
  ('Mouth-Melting Cheese Bites', 'Chipotle Chicken Taco', '', 245, '/menu/items/chipotle-chicken-taco.jpg'),
  ('Mouth-Melting Cheese Bites', 'Tangy Cottage Cheese Taco', '', 245, '/menu/items/tangy-cottage-cheese-taco.jpg'),
  ('Keffi Signatures', 'Falafel Platter', '', 295, '/menu/items/falafel-platter.jpg'),
  ('Keffi Signatures', 'Nachos with Salsa and Sour Cream', '', 245, '/menu/items/nachos-with-salsa-and-sour-cream.jpg'),
  ('Keffi Signatures', 'Cheese Garlic Bread', '', 195, '/menu/items/cheese-garlic-bread.jpg'),
  ('Pizza — Thin Crust', 'Margherita Pizza', '', 395, '/menu/items/margherita-pizza.jpg'),
  ('Pizza — Thin Crust', 'Mutton Pepperoni Pizza', '', 445, '/menu/items/mutton-pepperoni-pizza.jpg'),
  ('Pizza — Thin Crust', 'Chicken Tikka Pizza', '', 395, '/menu/items/chicken-tikka-pizza.jpg'),
  ('Pizza — Thin Crust', 'Bianca Pizza', '', 345, '/menu/items/bianca-pizza.jpg'),
  ('Pizza — Thin Crust', 'Farmhouse Vegetable Pizza', '', 395, '/menu/items/farmhouse-vegetable-pizza.jpg'),
  ('Pasta', 'Spaghetti — Pomodoro', 'Tomato basil sauce', 345, '/menu/items/spaghetti-pomodoro.jpg'),
  ('Pasta', 'Spaghetti — Arrabbiata', 'Spicy tomato sauce', 345, '/menu/items/spaghetti-arrabbiata.jpg'),
  ('Pasta', 'Spaghetti — Aglio e Olio', 'Garlic and olive oil', 345, '/menu/items/spaghetti-aglio-e-olio.jpg'),
  ('Pasta', 'Spaghetti — Alfredo', 'Creamy cheese sauce', 345, '/menu/items/spaghetti-alfredo.jpg'),
  ('Pasta', 'Spaghetti — Pink Sauce', 'Tomato-cream sauce', 345, '/menu/items/spaghetti-pink-sauce.jpg'),
  ('Pasta', 'Penne — Pomodoro', 'Tomato basil sauce', 345, '/menu/items/penne-pomodoro.jpg'),
  ('Pasta', 'Penne — Arrabbiata', 'Spicy tomato sauce', 345, '/menu/items/penne-arrabbiata.jpg'),
  ('Pasta', 'Penne — Aglio e Olio', 'Garlic and olive oil', 345, '/menu/items/penne-aglio-e-olio.jpg'),
  ('Pasta', 'Penne — Alfredo', 'Creamy cheese sauce', 345, '/menu/items/penne-alfredo.jpg'),
  ('Pasta', 'Penne — Pink Sauce', 'Tomato-cream sauce', 345, '/menu/items/penne-pink-sauce.jpg'),
  ('Pasta', 'Fettuccine — Pomodoro', 'Tomato basil sauce', 345, '/menu/items/fettuccine-pomodoro.jpg'),
  ('Pasta', 'Fettuccine — Arrabbiata', 'Spicy tomato sauce', 345, '/menu/items/fettuccine-arrabbiata.jpg'),
  ('Pasta', 'Fettuccine — Aglio e Olio', 'Garlic and olive oil', 345, '/menu/items/fettuccine-aglio-e-olio.jpg'),
  ('Pasta', 'Fettuccine — Alfredo', 'Creamy cheese sauce', 345, '/menu/items/fettuccine-alfredo.jpg'),
  ('Pasta', 'Fettuccine — Pink Sauce', 'Tomato-cream sauce', 345, '/menu/items/fettuccine-pink-sauce.jpg'),
  ('Desserts', 'Hot Chocolate Brownie', '', 245, '/menu/items/hot-chocolate-brownie.jpg'),
  ('Desserts', 'Chocolate Crunch Cake', '', 245, '/menu/items/chocolate-crunch-cake.jpg'),
  ('Desserts', 'Baked Yogurt & Granola', '', 225, '/menu/items/baked-yogurt-granola.jpg'),
  ('Desserts', 'Vegan Chocolate Cake', '', 245, '/menu/items/vegan-chocolate-cake.jpg'),
  ('Desserts', 'No-Bake Cheesecake', '', 265, '/menu/items/no-bake-cheesecake.jpg'),
  ('Add-ons', 'Chicken', 'Soup, salad, or pasta', 70, '/menu/items/chicken.jpg'),
  ('Add-ons', 'Prawns', 'Pasta add-on', 90, '/menu/items/prawns.jpg'),
  ('Add-ons', 'Vegetable', 'Pasta add-on', 70, '/menu/items/vegetable.jpg'),
  ('Add-ons', 'Cottage Cheese', 'Pasta add-on', 99, '/menu/items/cottage-cheese.jpg')
) as v(cat, name, description, price, image_url)
join menu_categories c on c.name = v.cat;

update cafe_settings
set app_name = 'Keffi',
    tagline = 'Crafted to Refresh',
    logo_url = '/keffi-logo.png'
where id = 1;
